stages:
  - build

.build:
  stage: build
  only:
    - master
  tags:
    - docker-shell
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$TAG_ID || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$TAG_ID --tag $CI_REGISTRY_IMAGE:$TAG_ID ./$TAG_ID
    - docker push $CI_REGISTRY_IMAGE:$TAG_ID


build:4.0.1:
  extends: .build
  variables:
    TAG_ID: 4.0.1

build:4.0.5:
  extends: .build
  variables:
    TAG_ID: 4.0.5

build:5.1.3:
  extends: .build
  variables:
    TAG_ID: 5.1.3

build:6.2.2:
  extends: .build
  variables:
    TAG_ID: 6.2.2

build:6.5.3:
  extends: .build
  variables:
    TAG_ID: 6.5.3
    
build:6.6.0:
  extends: .build
  variables:
    TAG_ID: 6.6.0